# Generated by Django 5.1.4 on 2025-01-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconstructionjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Files Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
